INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3863706', 'Model 3', 'Polestar');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8254949', 'E-Class', 'Bentley');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1536470', 'Ecosport', 'DFSK');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2398431', 'Inspire', 'Rolls-Royce');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7973139', 'Zafira', 'Ruf');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6096947', 'Sportage', 'Cadillac');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9929993', 'Tiguan', 'Polestar');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8778511', 'Reno', 'Piëch');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6528854', 'Durango', 'Land Rover');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('820497', 'TaTa', 'Cadillac');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('122858', 'Zohr', 'Fiat');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3518868', 'Sunny', 'Chrysler');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7388583', 'FJ Cruiser', 'Citroen');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2097159', 'Samara', 'DS Automobiles');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6506708', 'Crossland', 'AMC');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2656307', 'Challenger', 'Perodua');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5748523', 'Disco Volante', 'Hispano-Suiza');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6402619', 'Durango', 'Audi');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1129276', 'Mirage', 'Lincoln');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('70044', 'Kuga', 'Jimenez');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2189909', 'Levante', 'Oldsmobile');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3140620', 'Pathfinder', 'UAZ');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3748349', 'Compass', 'Ascari');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('400137', 'Twingo', 'DFSK');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1053593', 'Impreza', 'Daihatsu');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3174874', 'Range Rover', 'Shanghai Maple');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5245138', 'B-Class', 'De Tomaso');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3019313', 'Fusion', 'Bugatti');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6178197', 'Phaeton', 'PGO');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9445722', 'Velar', 'Ford Performance');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9997443', 'Encore', 'Brilliance');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7879457', 'Beetle', 'Rezvani');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('203913', 'Sienna', 'Donkervoort');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2263322', 'Scudo', 'Gumper');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2540131', 'F-Type', 'Dacia');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3968386', 'Granta', 'Rivian');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9728706', 'Torres', 'Citroen');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9789043', 'Levante', 'Chrysler');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('85780', 'Bolero', 'DFSK');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7216173', 'Telluride', 'Vauxhall Motors');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9518051', 'Tacoma', 'McLaren');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6970240', 'Wrangler', 'Bugatti');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4836045', 'Escalade', 'Plymouth');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('228432', 'Replay', 'Mini');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6224996', 'March', 'Prodrive');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5560877', 'Innova', 'Laffite');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3464330', 'Pathfinder', 'Vencer');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2716400', 'Savana', 'Voyah');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('958320', 'Amaze', 'Local Motors');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5273188', 'Corsa', 'Noble');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7005595', 'Crossland', 'Pagani');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('421486', 'Vision', 'Brilliance');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9213814', 'Maxima', 'Mazzanti');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2913116', 'RS7', 'Lada');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1443207', 'B-Class', 'Radical');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5487537', 'Golf', 'AMC');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5588517', 'Turbo', 'Farbio');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('661480', 'Aygo', 'AMC');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2070525', 'Zetao', 'Morgan');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6148532', 'Bronco', 'Audi');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5379078', 'Highlander', 'Hennessey');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8696175', 'Patrol', 'Bristol');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3457125', 'Ruby', 'NIO');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9764203', 'Espace', 'Yes');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5004504', 'Cerato', 'Martin');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3116273', 'Bluebird', 'Aurus');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4784396', 'Seltos', 'Ken Okuyama');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6809897', 'Legacy', 'Bugatti');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7860361', 'RS7', 'Gemballa');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2724348', 'Town & Country', 'Subaru');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3071803', 'Territory', 'Plymouth');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9000534', 'Explorer', 'Mazzanti');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7460745', 'Genesis', 'FAW');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4088898', 'Lancer', 'Fiat');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4954909', 'Charger', 'Eagle');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6894593', 'Legacy', 'Fab Design');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1915830', 'Bora', 'Lexus');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5644052', 'Sportage', 'Saipa');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2819106', 'Cadenza', 'Farboud');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1712880', 'Logan', 'DS Automobiles');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2995613', 'Edge', 'BMW');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('252525', 'Endeavour', 'Lancia');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2954049', 'Seltos', 'Honda');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1006807', 'E-Pace', 'Caterham');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9555869', 'Figo', 'Inferno');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3362566', 'Verna', 'Audi');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5196610', 'Aviator', 'Spyker');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5371333', 'Rajdoot', 'Skoda');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5268197', 'Atlas', 'Citroen');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4206040', 'Navara', 'Maserati');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6858460', 'Carina', 'De Tomaso');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6640162', 'Cascada', 'Rimac');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5881430', 'Rogue', 'Westfield');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2645152', 'Aygo', 'Volkswagen');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6153270', 'Rogue', 'Proton');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2494350', 'Crossland', 'Chrysler');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2252607', 'Levante', 'Holden');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('204661', 'Endeavour', 'Westfield');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6371476', 'Sapphire', 'DFSK');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6333363', 'Torres', 'Ferris');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8868055', 'Quattroporte', 'Lamborghini');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5162280', 'Rainier', 'Plymouth');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2655453', 'Sonic', 'Homark');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8212464', 'Telluride', 'Perodua');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7462969', 'i30', 'Fiat');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3884043', 'Legacy', 'TVR');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('135871', 'Escalade', 'Hyundai');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7338084', 'i8', 'Aspark');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('116953', 'Ranger', 'Farbio');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9204246', 'Raider', 'Pininfarina');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8398550', 'Avancier', 'Bollinger');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2362871', 'Cayman', 'Microcar');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5233360', 'E-Class', 'Brabus');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4788455', 'Tharson', 'Yes');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8631686', 'Caprice', 'Caterham');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2332287', 'Scorpio', 'Borgward');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5132586', 'Avalon', 'Mitsuoka');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('197504', 'Ruby', 'Praga');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('218182', 'Outlander', 'Toyota');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8574769', 'Safari', 'Gemballa');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2618123', 'Timor', 'Zagato');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2151917', 'QX70', 'Trion');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8575589', 'Ranger', 'IKCO');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('406334', 'Premio', 'Marussia');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7434482', 'Land Cruiser', 'Vector Motors');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3437143', 'Tucson', 'Volvo');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4614465', 'Cefiro', 'BAIC');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6940155', 'Defender', 'KTM');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6074945', 'Monte Carlo', 'GAC');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2546532', 'Nubira', 'Oldsmobile');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('415094', 'Transit', 'Voyah');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7516609', 'Telluride', 'Honda');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5874843', 'NV200', 'Gemballa');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5346614', 'Timor', 'Dacia');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3368686', 'Kontur', 'Fisker');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1888784', 'Evoque', 'Levdeo');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4218696', 'Grand Vitara', 'XPeng');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8587560', 'Santana', 'Victor');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7111966', 'Zohr', 'Roewe');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8281810', 'Navigator', 'Kleemann');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4871686', 'Escalade', 'UAZ');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5483407', 'Telcoline', 'Westfield');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5188709', 'Durango', 'Voyah');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9778096', 'Tharson', 'Martin');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6329709', 'Cullinan', 'Volkswagen');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1575152', 'Testarossa', 'VINFAST');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9027330', 'Romeo', 'Eagle');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4565017', 'Bolero', 'GMC');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5308933', 'Verna', 'Rimac');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4003936', 'Elantra', 'Rezvani');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8650551', 'Colorado', 'Tesla');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1805858', 'Impreza', 'Hennessey');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7491469', 'Ateca', 'Honda');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7696769', 'Lodgy', 'IKCO');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1200643', 'Ignis', 'Mini');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2392403', 'Volvo V40', 'Pininfarina');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7683993', 'Disco Volante', 'Vauxhall');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5150716', 'Town & Country', 'Hispano-Suiza');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2579625', 'Maxima', 'Mitsubishi');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1143545', 'Innova', 'Victor');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3281978', 'Zetao', 'Jaguar');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7077980', 'Fit', 'Pininfarina');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1903009', 'Durango', 'Farboud');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4448179', 'Ghibli', 'Fab Design');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1957212', 'Rush', 'Great Wall');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1534113', 'Spyder', 'Italdesign');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4999949', 'Sienna', 'Mercedes-Benz');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2229266', 'Twingo', 'Rolls-Royce');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9597274', 'C-HR', 'Zotye');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8694325', 'Amaze', 'Volvo');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('765730', 'Indigo', 'Roewe');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3679440', 'Genesis', 'Spyker');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1997649', 'Vision', 'Vector Motors');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9262116', 'Thar', 'NIO');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2797464', 'Outback', 'Mini');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8913831', 'Liana', 'Hyundai');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5311259', 'Koenigsegg', 'EdisonFuture');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9248844', 'Town & Country', 'Faraday Future');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6249419', 'Jimny', 'Vector Motors');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('18564', 'Jimny', 'FAW');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1713552', 'C-HR', 'Subaru');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2730787', 'Macan', 'Mitsubishi');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6674751', 'Cefiro', 'Jimenez');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4543635', 'Pathfinder', 'Vencer');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6781773', 'Grand Vitara', 'Vector Motors');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9276052', 'Sapphire', 'Ford');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6221120', 'Space', 'Lexus');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('100977', 'Cullinan', 'Brilliance');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7708792', 'Altima', 'Daihatsu');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8373865', 'H1', 'Maxus');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5761529', 'Matrix', 'Westfield');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1126683', 'Delica', 'Haval');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4085184', 'Bora', 'Hispano-Suiza');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6111247', 'Picanto', 'Hyundai');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1847320', 'Safari', 'Shelby');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2835877', 'Telcoline', 'Pure');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9574341', 'Civic', 'Jeep');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3396764', 'Evoque', 'Lexus');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1730552', 'Cayenne', 'NIO');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5007144', 'Flex', 'Hispano-Suiza');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('989137', 'QQ', 'MW Motors');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3052344', 'Picanto', 'Noble');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5231289', 'Amaze', 'Ruf');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7395195', 'Strada', 'KTM');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9681666', 'Kodiaq', 'Mercedes-Benz');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7831879', 'Tharson', 'GTA Hispano');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9732096', 'Carnival', 'Proton');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7178751', 'Maranello', 'Mahindra');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('89585', 'Indigo', 'Lightyear');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9804519', 'Disco Volante', 'Changan');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2121369', 'Model Y', 'Daewoo');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2462661', 'Vanquish', 'Land Rover');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5303297', 'Camaro', 'Maybach');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2641663', 'Cefiro', 'Chevrolet');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9039434', 'Logan', 'NIO');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1033990', 'Galant', 'Karma');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4931859', 'Vision', 'Rolls-Royce');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3369190', 'XL6', 'Leblanc');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9566053', 'Camaro', 'Peugeot');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7151509', 'Rally', 'Lancia');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1308246', 'Teramont', 'Ascari');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1626339', 'Tiago', 'Buick');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6154995', 'ProAce', 'Studebaker');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6267406', 'Onix', 'Spyker Cars');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3939143', 'TaTa', 'Lamborghini');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1768309', 'Bullet', 'Hispano-Suiza');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1252307', 'Kuga', 'Audi');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('568058', 'C-Class', 'Volga');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6282853', 'Nutme', 'RAM');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7353779', 'Amaze', 'Iveco');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3950898', 'Velar', 'Skoda');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3871155', 'Tharson', 'Lincoln');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8355091', 'Delta', 'Roewe');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('548411', 'Cruze', 'Skoda');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('781546', 'Rebel', 'Lucid');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9882079', 'Chevelle', 'Koenigsegg');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9451417', 'Revero', 'Mazda');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4466407', 'Mustang', 'Plymouth');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('801159', 'Lucerne', 'KTec');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('223090', 'Picanto', 'Aspark');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6162191', 'B-Class', 'Geely');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7975109', 'Savana', 'Vauxhall Motors');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6863704', 'Indigo', 'Shuanghuan');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4963651', 'Model X', 'Vauxhall Motors');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('914210', 'Model X', 'Vauxhall');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9367111', 'Chevelle', 'Buick');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('17769', 'Koenigsegg', 'KTM');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3584819', 'Thunderbird', 'IKCO');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9478204', 'Ignis', 'Volvo');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2320681', 'C-HR', 'Leblanc');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9277874', 'Corolla', 'Honda');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('845731', 'Zonda', 'Koenigsegg');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1008835', 'Kicks', 'Fiat');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5167531', 'Legacy', 'Seat');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5544329', 'Cefiro', 'Ken Okuyama');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2089203', 'Aygo', 'Venucia');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2239582', 'Ka', 'Maxus');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1453977', 'Glanza', 'Vanda Electrics');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3515883', 'Fleetwood', 'Seat');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9168398', 'Verna', 'RAM');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('948978', 'Centodieci', 'Brilliance');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5017272', 'Storm', 'GMC');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6588610', 'Miata', 'Zagato');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6164738', 'Durango', 'Hispano-Suiza');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2222070', 'Storm', 'Mazda');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9136483', 'Puma', 'Citroen');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1725118', 'Cascada', 'Polestar');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('760298', 'Thunderbird', 'Dacia');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2010544', 'Forte', 'Polestar');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9106467', 'D-Max', 'Bugatti');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9710338', 'Yukon', 'Bizzarrini');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4504165', 'i10', 'Josse');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6491976', 'Gladiator', 'Borgward');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7220653', 'Rosso', 'Mazzanti');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9365587', 'California', 'Roewe');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2092727', 'Touran', 'IKCO');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9007554', 'Explorer', 'Peugeot');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6684349', 'Vivio', 'Victor');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7514218', 'Galant', 'Superformance');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5570660', 'Courier', 'Tata');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1602833', 'Venue', 'Proton');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7680457', 'Panamera', 'Piëch');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2673535', 'RS8', 'Hispano-Suiza');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8659729', 'i8', 'KTM');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7923744', 'Neo', 'Radical');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5393808', 'Terracan', 'Hyundai');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9155046', 'Crosspolo', 'Nissan');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7556867', 'Caprice', 'Shanghai Maple');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1678269', 'Replay', 'Kleemann');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7344918', 'Avensis', 'TechArt');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8160283', 'Santana', 'Toyota');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8968330', 'Regal', 'Ariel');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6713792', 'Escort', 'Daewoo');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1156648', 'Portofino', 'Ford Performance');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8656979', 'BrZ', 'Bristol');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5112669', 'Qashqai', 'Lamborghini');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2390000', 'Rexton', 'Chrysler');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9167596', 'Esprit', 'Noble');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2622417', 'Trailblazer', 'Westfield');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9579981', 'Tiago', 'Studebaker');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8218771', 'Replay', 'Homark');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6255461', 'Grand Vitara', 'Infiniti');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7193252', 'Optima', 'Infiniti');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1063472', 'Pilot', 'Ferris');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5593265', 'Turismo', 'Nissan');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8126623', 'Rosso', 'Saipa');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1703700', 'Cayman', 'RAM');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6702873', 'Jimny', 'Gumper');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7152297', 'Accord Crosstour', 'JAC');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5817082', 'Novus', 'OSCA');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5985783', 'Legacy', 'Isuzu');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9145834', 'Compass', 'Seat');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('34587', 'RS8', 'Alpina');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5891204', 'Turismo', 'Brilliance');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7728328', 'Orion', 'Bizzarrini');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3571268', 'Malibu', 'GMC');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7984675', 'Telcoline', 'Ferrari');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6082583', 'Bullet', 'Zagato');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9445036', 'Pilot', 'Holden');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9977894', 'Quattroporte', 'Scion');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1181309', 'Outback', 'AMC');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7715405', 'B-Series', 'Superformance');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1705521', 'Brio', 'GMC');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7830525', 'Malibu', 'Dacia');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7407158', 'Charger', 'Aspark');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9112542', 'Camaro', 'Lincoln');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1852051', 'Terracan', 'FAW');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7882275', 'Vitara', 'Noble');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1564809', 'GranTurismo', 'Genesis');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8599728', 'Picanto', 'Bristol');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5666700', 'Magnum', 'Pagani');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7952222', 'March', 'Farbio');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8004359', 'Picanto', 'Radical');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1661610', 'Explorer', 'Nissan');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4938651', 'Matrix', 'Spectre');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8916145', 'Civic', 'Polestar');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8389979', 'Dart', 'Opel');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4498357', 'Kolasin', 'Lexus');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8439543', 'Maxima', 'Mini');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9737638', 'Orion', 'Bentley');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1332611', 'Santa Fe', 'Martin');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1081215', 'Cullinan', 'Rezvani');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8360925', 'Compass', 'Radical Sportscars');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6788092', 'Grand Vitara', 'Scuderia Cameron');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3265026', 'Figo', 'Ferrari');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9499895', 'Durango', 'Ariel');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('346877', 'Kicks', 'Ruf');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9862635', 'Land Cruiser', 'Saturn');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('803994', 'Santana', 'Seat');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9209256', 'Voyager', 'SSC North America');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('833752', 'Kolasin', 'IKCO');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7710773', 'Kuga', 'Proton');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4494514', 'Accord Crosstour', 'Huansu');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9244233', 'Turismo', 'Ginetta');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5240524', 'QX60', 'Lincoln');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6780405', 'Ranger', 'Bugatti');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9392390', 'TaTa', 'Vector Motors');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3445558', 'Pilot', 'Audi');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7342564', 'Challenger', 'KTec');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2718272', 'Puma', 'Thunder Power');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2207771', 'C-HR', 'Ascari');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3113119', 'Rosso', 'Volkswagen');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7706558', 'QX50', 'Jaguar');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6434088', 'Premio', 'Alpina');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3903350', 'Encore', 'Honda');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7042045', 'Orion', 'Toyota');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('94216', 'Pulsar', 'Honda');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4285963', 'Datsun', 'Buick');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8730888', 'Fiesta', 'Peugeot');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7480798', 'Espace', 'Maserati');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7692374', 'Evoque', 'TVR');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6354532', 'i30', 'Hispano-Suiza');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4158507', 'Palisa', 'Venucia');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7885686', 'Aviator', 'Bugatti');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1526809', 'Suburban', 'Aspark');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('917703', 'Ka', 'Alpina');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8915351', 'Zonda', 'Saturn');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7098505', 'Carrera', 'KTM');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9878547', 'Carens', 'Marussia');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3689717', 'Touran', 'Maybach');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('259810', 'Bullet', 'Donkervoort');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2528944', 'Suburban', 'Fab Design');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7246071', 'Highlander', 'Jimenez');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6106673', 'Rexton', 'Koenigsegg');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4766570', 'Tracker', 'Yes');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8204852', 'Caliber', 'Radical');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2989832', 'Tahoe', 'Spectre');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5115512', 'Tomahawk', 'RAM');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5035527', 'Navara', 'Volkswagen');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9817323', 'Bullet', 'Bentley');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4452431', 'Dart', 'Westfield');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9317135', 'Matrix', 'Heuliez');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5405666', 'QX70', 'Great Wall');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6457605', 'Mii', 'Spyker Cars');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8630751', 'Tucson', 'KTec');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('754427', 'Maruti', 'Roewe');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6675376', 'Grandis', 'Mahindra');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7436002', 'Passat', 'Mitsuoka');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8473645', 'ProAce', 'Icona');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8280458', 'Yaris', 'King Long');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1580910', 'Palio', 'NIO');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3778321', 'Espace', 'Subaru');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('148396', 'Grand Vitara', 'Mazda');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8412670', 'C-Class', 'Spectre');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3369165', 'Nutme', 'Audi');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1259046', 'Taigun', 'McLaren');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8276339', 'Turismo', 'Aspark');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('68968', 'ProAce', 'Victor');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9740302', 'Stelvio', 'Kleemann');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4312065', 'BrZ', 'Volkswagen');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9470733', 'Torres', 'Opel');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3746681', 'Raider', 'Westfield');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8862863', 'Boxer', 'Aspark');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9390267', 'Kuga', 'Farbio');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6331745', 'Ka', 'Hummer');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6970869', 'Regal', 'Daihatsu');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8038158', 'Tracker', 'Hummer');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9186864', 'Wrangler', 'Piëch');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('954045', 'i10', 'Vauxhall Motors');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5217624', 'Santana', 'Subaru');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6205163', 'Strada', 'Mercedes-Benz');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('44600', 'Staria', 'Venucia');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('904377', 'Nubira', 'Superformance');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1290249', 'RS8', 'Microcar');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9149633', 'Testarossa', 'AMC');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9038481', 'Continental', 'DFSK');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5525245', 'Renegade', 'WEY');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('614088', 'Speeder', 'Laffite');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1073491', 'Trezia', 'Luxgen');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2637384', 'Zetao', 'Huansu');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8685211', 'Cybertruck', 'Scuderia Cameron');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3461197', 'Touran', 'SSC North America');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9701936', 'ProAce', 'Nissan');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4160015', 'Rogue', 'Volkswagen');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('882842', 'Altima', 'Lucid');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3981658', 'Rosso', 'Honda');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1841907', 'Escape', 'Bollinger');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8589674', 'Silk', 'Shuanghuan');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2558760', 'Granta', 'Gemballa');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4242384', 'Talisman', 'Westfield');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4064445', 'Rio', 'Marussia');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7826899', 'Orion', 'Chery');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1286143', 'Model X', 'FAW');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9981940', 'Pilot', 'Proton');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3598065', 'Telluride', 'Seat');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7557672', 'Romeo', 'Fab Design');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9106645', 'Rhino', 'Bugatti');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9338906', 'Cefiro', 'Prodrive');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6280402', 'Range Rover', 'Honda');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7540447', 'Rush', 'Vanda Electrics');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2996886', 'GT-R', 'HKS');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8833337', 'Escalade', 'Proton');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9026510', 'Arona', 'Eagle');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5013867', 'Kontur', 'FAW');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('477353', 'Cybertruck', 'Mitsuoka');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2128387', 'March', 'Lincoln');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6891284', 'Sonic', 'HKS');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('178532', 'Urban Cruiser', 'Piëch');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7995720', 'Timor', 'Isuzu');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('468949', 'Urban Cruiser', 'Shuanghuan');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3652508', 'Phantom', 'Saturn');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('476357', 'E-Type', 'Changan');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9000548', 'Velar', 'Chery');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('51694', 'Odyssey', 'Piëch');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5067549', 'Cullinan', 'Tesla');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7545826', 'Nexon', 'Kleemann');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3086877', 'Tiago', 'Lexus');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6080905', 'Explorer', 'Saturn');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5888939', 'Fiesta', 'RAM');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7245510', 'Rogue', 'TVR');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3790664', 'Raum', 'Kia');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7281353', 'Timor', 'Saipa');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6605013', 'Malibu', 'Proton');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4426687', 'Navara', 'Jimenez');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8697338', 'Forte', 'Alpina');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('728928', 'Golf', 'Aspark');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('5332375', 'i8', 'Audi');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4193758', 'Clio', 'Skoda');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1134050', 'Turbo', 'Laffite');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('2480998', 'Grandis', 'OSCA');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1050003', 'Pilot', 'Roewe');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8101870', 'Novus', 'Microcar');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3267903', 'Yukon', 'Shanghai Maple');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6701159', 'Maruti', 'KTM');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7956075', 'Thunderbird', 'Jimenez');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7360303', 'Novus', 'Rolls-Royce');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8966429', 'Passat', 'Jeep');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4166002', 'Boxster', 'Shuanghuan');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('9734599', 'Stratos', 'HKS');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('3450908', 'Replay', 'EdisonFuture');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1351269', 'Tomahawk', 'Morgan');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('107225', 'Inspire', 'Leblanc');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('6330012', 'Enzo', 'Peugeot');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('1920004', 'Challenger', 'Tesla');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('216642', 'Urus', 'Heuliez');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('4314274', 'Tiago', 'Trion');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8870711', 'Silk', 'Citroen');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('8299737', 'Outlander', 'Tesla');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('7536614', 'Datsun', 'PGO');
INSERT INTO Vehicle (License_num, Model, Type) VALUES ('221902', 'Swift', 'Heuliez');

commit;
