SELECT * FROM Soldier;
SELECT * FROM Vehicle;
SELECT * FROM Product;
SELECT * FROM Driver;
SELECT * FROM Shekem;
SELECT * FROM Delivery;
SELECT * FROM Brings_to;
SELECT * FROM Seller;
SELECT * FROM Has;
